"""Closed scientific vocabulary for the cross-ID formalism recovery mission."""
from __future__ import annotations

from .cross_observer_grouping import *  # stable canonical JSON and integrity helpers

MISSION_ID = "OC3-CROSS-ID-FORMALISM-RECOVERY-AUTONOMY-001"

REOPENED_CLAIMS = (
    "CROSS_IDENTIFICATION_FORMALISM_ASSUMPTIONS",
    "BOUNDED_PILOT_SPECIFIABLE_WITHOUT_THRESHOLD",
)

FORMALISM_CLAIMS = (
    "A_BAYESIAN_PROBABILISTIC",
    "B_SAME_SOURCE_VS_SEPARATE_SOURCE",
    "C_SYMMETRY",
    "D_POSITIONAL_UNCERTAINTY_MODEL",
    "E_KNOWN_POSITIONAL_UNCERTAINTIES",
    "F_CIRCULAR_GAUSSIAN_SPHERICAL_APPROXIMATIONS",
    "G_PRIORS",
    "H_POINT_SOURCE_ASSUMPTION",
    "I_OPTIONAL_PHYSICAL_PROPERTIES",
    "J_EXTENDED_DR9_GALAXY_TRANSFER_LIMIT",
    "K_NO_ARBITRARY_MATCH_DECISION_RADIUS_REQUIREMENT",
)

EPISTEMIC_LAYERS = (
    "FORMALISM_FACT",
    "DR9_DATA_FACT",
    "PROJECT_SUITABILITY_INFERENCE",
)

BOUND_TYPES = (
    "CANDIDATE_GENERATION_SEARCH_BOUND",
    "SCIENTIFIC_MATCH_DECISION_THRESHOLD",
)

TERMINAL_OUTCOMES = (
    "CROSS_ID_FORMALISM_RECOVERED_PILOT_SPECIFIABLE",
    "CROSS_ID_FORMALISM_RECOVERED_PILOT_STILL_UNRESOLVED",
    "CROSS_ID_FORMALISM_EVIDENCE_INCONCLUSIVE",
    "CROSS_ID_FORMALISM_CONFLICT",
)


def validate_claim_vocabulary() -> None:
    if len(FORMALISM_CLAIMS) != 11 or len(set(FORMALISM_CLAIMS)) != 11:
        raise ValueError("FORMALISM_CLAIM_VOCABULARY_INVALID")
    if "H_POINT_SOURCE_ASSUMPTION" not in FORMALISM_CLAIMS:
        raise ValueError("POINT_SOURCE_ASSUMPTION_MISSING")
    if "E_KNOWN_POSITIONAL_UNCERTAINTIES" not in FORMALISM_CLAIMS:
        raise ValueError("KNOWN_POSITIONAL_UNCERTAINTY_MISSING")
    if BOUND_TYPES[0] == BOUND_TYPES[1]:
        raise ValueError("SEARCH_BOUND_THRESHOLD_COLLAPSED")

